#!C:/Program\ Files/Git/usr/bin/sh.exe
echo
if [ -e .commit ]
    then
    rm .commit
    git add version.txt 
	git add version-dotted.txt 
	git add version-dotted-carry.txt
    git commit --amend -C HEAD --no-verify
fi
exit