#!C:/Program\ Files/Git/usr/bin/sh.exe
touch .commit
BRANCH=`git rev-parse --abbrev-ref HEAD`
exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\.githooks\Pre-Commit.ps1" -branch $BRANCH
exit